### ISSUE TITLE
If viable add ability to receive message and send messages to akka actors

### ISSUE THREAD

**Issue by softinio** [zio/zio-actors#119]

**Comment by gastonlucero** [comment]
Hi @softinio, I could look this issue, the idea is with typed or classic actors?

**Comment by mtsokol** [comment]
@gastonlucero I think we can start with typed as the latest 2.6 version recommends using new actor API

**Comment by softinio** [comment]
@gastonlucero All yours that would be wonderful thanks so much for helping us
