### ISSUE TITLE
Migrate project to CircleCI

### ISSUE THREAD

**Issue by softinio** [zio/zio-actors#23]
- Migrate Project to CircleCI
- Use CircleCi env variables for sonatype credentials
- Update README and code to use new name for repo

**Comment by NeQuissimus** [comment]
These have all been set to values that should work:

- PGP_PASSPHRASE
- PGP_SECRET
- SONATYPE_PASSWORD
- SONATYPE_USER

Note that `PGP_SECRET` is base64-encoded (as most sbt plugins expect)

You should be able to publish artifacts in the groupId `dev.zio`

**Comment by NeQuissimus** [comment]
I just did this with https://github.com/NeQuissimus/zio-slf4j/commit/7b415e760b7ac23c1d5bd54b5b8b9aa2e19b86fc if you need inspiration

**Comment by NeQuissimus** [comment]
I also set `PGP_PUBLIC` in `zio-actors` to be the base64-encoded public key

**Comment by softinio** [comment]
@NeQuissimus ty sir will use that if ok. Sorry you beat me to it time outside work has been challenging last few weeks :-)

**Comment by NeQuissimus** [comment]
I actually just make a context in Circle CI (https://circleci.com/docs/2.0/contexts/#creating-and-using-a-context) named "Sonatype".
You should use that instead of just assuming the ENV exists. I am deleting the variables on your job for you to use the context instead.
