### ISSUE TITLE
Switch from sbt-microsites to docusaurus

### ISSUE THREAD

**Issue by softinio** [zio/zio-actors#25]
https://scalameta.org/mdoc/docs/docusaurus.html

**Comment by mijicd** [comment]
Shall we close this one?

**Comment by LGLO** [comment]
circleci file contains task named `microsite` that launches `./sbt docs/docusaurusCreateSite`
Contributing.md references to zio site as microsite. Let me take care of this cleanup and I'll close ticket when done.

**Comment by LGLO** [comment]
I was totally distracted when giving previous answer. I was looking into zio, not zio-actors.
Looks like zio-actors documentation page is 404, there is still a ticket for writing content for it.
I mean we could change ticket to write documentation with docusaurus and we need one to put documentation online.

**Comment by softinio** [comment]
Its done so closing
