### ISSUE TITLE
Add support for mysql for persistence

### ISSUE THREAD

**Issue by jupposessho** [zio/zio-actors#258]
The idea is to add a new field to the config called "driver".
Then we can set the driver on the data source(ds.setDriverClassName(dbConfig.dbDriver.value)).

Question: should we add the mysql driver as a dependency or the users will add it if they want to use mysql for persistence?

**Comment by mtsokol** [comment]
@jupposessho Hi! Thanks for the issue and PR. If you don't mind I can take a look this weekend!

**Comment by jupposessho** [comment]
The current implementation is working with the following Mysql table:

`create table if not exists journal_zio
(
    persistence_id varchar not null,
    sequence_number unsigned int not null auto_increment,
    message bytea,
        primary key (persistence_id, sequence_number)
);`

in application.conf:
`mysqlActorSystem.zio.actors.persistence {
  plugin = "jdbc-journal"
  url    = "jdbc:mysql://localhost:3306/dbname"
  user   = "user"
  pass   = "password"
}`

the mysql driver should be added as a dependency in build.sbt:
`"mysql" % "mysql-connector-java" % "8.0.20"`
