### ISSUE TITLE
CircleCI Release job fails

### ISSUE THREAD

**Issue by softinio** [zio/zio-actors#26]
## Circle Release Job issues

- The release job fails waiting for GPG password to be entered at the `sbt releaseEarly` step resolve. 

- Also check if its correct to use `dev.zio` as the Sonatype org name

Sample Failed build:

https://circleci.com/gh/zio/zio-actors/23

Error:

`Please enter PGP passphrase (or ENTER to abort): Too long with no output (exceeded 10m0s)`

**Comment by NeQuissimus** [comment]
I fixed this issue but now there is a new one. I commented on https://issues.sonatype.org/browse/OSSRH-47886 for Sonatype to figure it out

**Comment by softinio** [comment]
@NeQuissimus Thank you!

**Comment by NeQuissimus** [comment]
https://oss.sonatype.org/service/local/repositories/releases/content/dev/zio/zio-actors_2.12/0.0.1+9-e61a224d/zio-actors_2.12-0.0.1+9-e61a224d.jar

**Comment by NeQuissimus** [comment]
Can you look at https://circleci.com/gh/zio/zio-actors/34 ?
I think the microsite publishing tries to do something weird but I can't figure it out

**Comment by softinio** [comment]
Great news. Awesome seeing it published. 

Yes will look into that issue. Going to make some other tweaks to build too, seems it runs the microsite job on merge to master without tags which needs fixing.
