### ISSUE TITLE
Importing and creating a stateful actor and overriding receive gives error

### ISSUE THREAD

**Issue by akilegaspi** [zio/zio-actors#47]
Getting a `receive has incompatible type` compile error when using the code from the Test Suite directly to the `run` method

**Comment by mtsokol** [comment]
Today encountered same issue. Examples from tests aren't compiling.

**Comment by mtsokol** [comment]
@akilegaspi Hi, the examples from tests are compiling and running correctly with the latest version! 🙂 

@softinio Should we close this?

**Comment by akilegaspi** [comment]
I haven't actually tried it again since I was waiting for some updates to the repository but I'll be trying it now and give a report!

**Comment by akilegaspi** [comment]
Nevermind, I think this should be closed already.

Thank you for your contribution @mtsokol !

**Comment by softinio** [comment]
Yup closing 👍
